{% set name = "bottom" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ClementTsang/bottom/archive/{{ version }}.tar.gz
  sha256: 1db45fe9bc1fabb62d67bf8a1ea50c96e78ff4d2a5e25bf8ae8880e3ad5af80a

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    # - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - btm --help

about:
  home: https://clementtsang.github.io/bottom
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Yet another cross-platform graphical process/system monitor
  dev_url: https://github.com/ClementTsang/bottom

extra:
  recipe-maintainers:
    - danielnachun
