context:
  version: "0.14.7"

package:
  name: bottom
  version: ${{ version }}

source:
  url: https://github.com/ClementTsang/bottom/archive/${{ version }}.tar.gz
  sha256: 249fca780922460278fffa2c3697a30c8a5483d06c14e66f093f51234d49c50c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - btm --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Yet another cross-platform graphical process/system monitor
  homepage: https://clementtsang.github.io/bottom
  repository: https://github.com/ClementTsang/bottom

extra:
  recipe-maintainers:
    - danielnachun
