context:
  version: "0.11.3"

package:
  name: bottom
  version: ${{ version }}

source:
  url: https://github.com/ClementTsang/bottom/archive/${{ version }}.tar.gz
  sha256: f5d286c2950379a310be2042271c4bd772ef66947bf1ca16e5a169115774745c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - btm --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Yet another cross-platform graphical process/system monitor
  homepage: https://clementtsang.github.io/bottom
  repository: https://github.com/ClementTsang/bottom

extra:
  recipe-maintainers:
    - danielnachun
